name: publish
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - run: dotnet test XUnit.Extensions.MaxParallelization.sln --configuration Release
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: XUnit.Extensions.MaxParallelization/XUnit.Extensions.MaxParallelization.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: XUnit.Extensions.MaxParallelization
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.NUGETKEY }}
